### ISSUE TITLE
Separate cmxs incompatible with makefiles

### ISSUE THREAD

**Issue by maximedenes** [maximedenes/native-coq#4]
If we want developments using native compilation to be compatible with regular makefiles, we should store the compiled code in vo files.

**Comment by ckeller** [comment]
Does it mean that now, `make install` works directly with a `Makefile` generated with `coq_makefile`?

**Comment by maximedenes** [comment]
In Coq 8.5 and trunk yes. In the native-coq branch, I should double check indeed.
